export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const NOTICE_REQUEST = 'NOTICE_REQUEST'
export const NOTICE_SUCCESS = 'NOTICE_SUCCESS'
export const NOTICE_FAIL = 'NOTICE_FAIL'

export const FACULTY_REQUEST = 'FACULTY_REQUEST'
export const FACULTY_SUCCESS = 'FACULTY_SUCCESS'
export const FACULTY_FAIL = 'FACULTY_FAIL'

export const FACULTY_DETAILS_REQUEST = 'FACULTY_DETAILS_REQUEST'
export const FACULTY_DETAILS_SUCCESS = 'FACULTY_DETAILS_SUCCESS'
export const FACULTY_DETAILS_FAIL = 'FACULTY_DETAILS_FAIL'

export const PUBLICATIONS_REQUEST = 'PUBLICATIONS_REQUEST'
export const PUBLICATIONS_SUCCESS = 'PUBLICATIONS_SUCCESS'
export const PUBLICATIONS_FAIL = 'PUBLICATIONS_FAIL'

