export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const NOTICE_REQUEST = 'NOTICE_REQUEST'
export const NOTICE_SUCCESS = 'NOTICE_SUCCESS'
export const NOTICE_FAIL = 'NOTICE_FAIL'

export const NOTICE_CREATE_REQUEST = 'NOTICE_CREATE_REQUEST'
export const NOTICE_CREATE_SUCCESS = 'NOTICE_CREATE_SUCCESS'
export const NOTICE_CREATE_FAIL = 'NOTICE_CREATE_FAIL'

export const NOTICE_EDIT_REQUEST = 'NOTICE_EDIT_REQUEST'
export const NOTICE_EDIT_SUCCESS = 'NOTICE_EDIT_SUCCESS'
export const NOTICE_EDIT_FAIL = 'NOTICE_EDIT_FAIL'

export const NOTICE_DELETE_REQUEST = 'NOTICE_DELETE_REQUEST'
export const NOTICE_DELETE_SUCCESS = 'NOTICE_DELETE_SUCCESS'
export const NOTICE_DELETE_FAIL = 'NOTICE_DELETE_FAIL'

export const FACULTY_REQUEST = 'FACULTY_REQUEST'
export const FACULTY_SUCCESS = 'FACULTY_SUCCESS'
export const FACULTY_FAIL = 'FACULTY_FAIL'

export const FACULTY_DETAILS_REQUEST = 'FACULTY_DETAILS_REQUEST'
export const FACULTY_DETAILS_SUCCESS = 'FACULTY_DETAILS_SUCCESS'
export const FACULTY_DETAILS_FAIL = 'FACULTY_DETAILS_FAIL'

export const PUBLICATIONS_REQUEST = 'PUBLICATIONS_REQUEST'
export const PUBLICATIONS_SUCCESS = 'PUBLICATIONS_SUCCESS'
export const PUBLICATIONS_FAIL = 'PUBLICATIONS_FAIL'

export const VISITOR_MESSAGE_SEND_REQUEST = 'VISITOR_MESSAGE_SEND_REQUEST'
export const VISITOR_MESSAGE_SEND_SUCCESS = 'VISITOR_MESSAGE_SEND_SUCCESS'
export const VISITOR_MESSAGE_SEND_FAIL = 'VISITOR_MESSAGE_SEND_FAIL'
export const VISITOR_MESSAGE_SEND_RESET = ' VISITOR_MESSAGE_SEND_RESET'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'

export const FACULTY_PROFILE_REQUEST = 'FACULTY_PROFILE_REQUEST'
export const FACULTY_PROFILE_SUCCESS = 'FACULTY_PROFILE_SUCCESS'
export const FACULTY_PROFILE_FAIL = 'FACULTY_PROFILE_FAIL'

export const FACULTY_PROFILE_CREATE_REQUEST = 'FACULTY_PROFILE_CREATE_REQUEST'
export const FACULTY_PROFILE_CREATE_SUCCESS = 'FACULTY_PROFILE_CREATE_SUCCESS'
export const FACULTY_PROFILE_CREATE_FAIL = 'FACULTY_PROFILE_CREATE_FAIL'


